const POSTAL_REQUIRED_ERROR = 'POSTAL_REQUIRED_ERROR'
const GOOGLE_MAP_GEOCODE_EMPTY_RESULT = 'GOOGLE_MAP_GEOCODE_EMPTY_RESULT'
const GOOGLE_MAP_TIMEZONE_EMPTY_RESULT = 'GOOGLE_MAP_TIMEZONE_EMPTY_RESULT'

module.exports = {
  POSTAL_REQUIRED_ERROR,
  GOOGLE_MAP_GEOCODE_EMPTY_RESULT,
  GOOGLE_MAP_TIMEZONE_EMPTY_RESULT
}